[[colors.indexed_colors]]
color = "#ff9e64"
index = 16

[[colors.indexed_colors]]
color = "#db4b4b"
index = 17

[colors.bright]
black = "0x7f8490"
blue = "0x76cce0"
cyan = "0xf39660"
green = "0x9ed072"
magenta = "0xb39df3"
red = "0xfc5d7c"
white = "0xe2e2e3"
yellow = "0xe7c664"

[colors.normal]
black = "0x181819"
blue = "0x76cce0"
cyan = "0xf39660"
green = "0x9ed072"
magenta = "0xb39df3"
red = "0xfc5d7c"
white = "0xe2e2e3"
yellow = "0xe7c664"

[colors.primary]
# background = "0x2c2e34"
# foreground = "0xe2e2e3"

[env]
TERM = "xterm-256color"

[font]
size = 20.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "alacritty -e 'btop' & \r"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "search_history \r"
key = "Slash"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "End"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001B[5;2~"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;5~"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"

[[keyboard.bindings]]
chars = "\u001B[6;2~"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "o"
key = "Delete"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "Back"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u0018,"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018("
key = "N"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018)"
key = "N"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018'"
key = "P"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018("
key = "P"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018B"
key = "T"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018C"
key = "T"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018#"
key = "R"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018$"
key = "R"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0018<"
key = "Comma"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0017>"
key = "Period"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u000B,"
key = "Comma"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018m"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018a"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018d"
key = "D"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018v"
key = "V"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018s"
key = "A"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018V"
key = "S"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018\b"
key = "H"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = """
\u0018
"""
key = "J"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018\u000B"
key = "K"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018\f"
key = "L"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u00181"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00182"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00183"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00184"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00185"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00186"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00187"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00188"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00189"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018x"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018w"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018/"
key = "Slash"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u0018,"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018="
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018o"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018z"
key = "O"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018z"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018\u0001"
key = "Escape"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018\u0010"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018\u000E"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018\t"
key = "F"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u0018\t"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018n"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018p"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018/"
key = "Slash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018!"
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018$"
key = "I"
mods = "Shift|Command"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0006v"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006s"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0006x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00061"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00062"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00063"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00064"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00065"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00066"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00067"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00068"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00069"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007Q"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006L"
key = "Right"
mods = "Command"

[shell]
args = ["-l", "-c", "session_name=$(tmux ls | grep -v \"(attached)\" | head -n 1 | cut -d: -f1); [ -n \"$session_name\" ] && tmux attach -t \"$session_name\" || tmux new-session"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
decorations_theme_variant = "None"
dynamic_padding = false
dynamic_title = true
opacity = 1

[window.padding]
x = 10
y = 10
